name: Rodar Testes Automaticamente
# Descrição: Este workflow é acionado automaticamente em push ou pull request para os branches main e E2E_MAIN.
on:
  push:
    branches: [ main, E2E_MAIN ]
  pull_request:
    branches: [ main, E2E_MAIN ]
jobs:
  E2E-Tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30